##DEV DATABASE CONFIGURATION, PLEASE KEEP IT AS IT IS
spring:
  datasource:
    url: jdbc:postgresql://ep-billowing-bread-a54fw5to.us-east-2.aws.neon.tech:5432/soen390-v1
    username: KA-devl
    password: v0PJRz3hgBfD
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
